CREATE TABLE IF NOT EXISTS tokens (
  id SERIAL PRIMARY KEY,
  token VARCHAR(255) UNIQUE NOT NULL,
  user_id INTEGER NOT NULL,
  expiry_date TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);